### ISSUE TITLE
[Epic] Next.js Template Tech Stack Selection

### ISSUE THREAD

**Issue by nabilashbat** [ByteRunners/NextJS-Sprout#4]
# Next.js Template Tech Stack

## Core Technologies

- [x] Next.js 14 App Router
- [x] React 18
- [x] TypeScript strict mode
- [x] Tailwind CSS

## Used Libraries

- [x] #5
- [x] #23
- [x] #20

###

- [ ] Health checks

###

- [x] #26
- [x] #31

###

- [x] #24
- [ ] Percy

###

- [ ] tRPC
- [x] #27
- [x] #25

###

- [x] #33

###

- [ ] helmet
- [ ] csurf
- [ ] #30  - [Link](https://nextjs.org/docs/app/building-your-application/configuring/content-security-policy)

###

- [x] #28
- [ ] SWR

###

- [ ] Workbox
- [ ] Next PWA

###

- [ ] Swagger
- [x] #35

###

- [ ] [SonarQube](https://www.mend.io/renovate/)
- [ ] New Relic
- [ ] a11y

## Developer Experience (DX)

- [x] #22
- [x] Stylelint #22
- [x] #7

###

- [x] #14
- [x] #15
- [x] #16
- [x] #17
- [x] #18
- [ ] GitHub Actions
- [ ] Automatic Branch and Issue Autolink
- [ ] Semantic Release
- [ ] Release Please
- [ ] Snippets
- [ ] Absolute Imports and Path Alias
- [x] #9
- [x] #29
- [x] #6
- [x] Engine and packages configs #6 
- [ ] Patch Package
- [ ] AI Code Review
- [ ] Axe Accessibility Checker
- [x] #11 [Dependabot](https://docs.github.com/en/code-security/dependabot)

#

---

**To consider using**

- [ ] React Hook Form
- [ ] MirageJS
- [ ] Site Map - next-sitemap
- [ ] Bundler Analyzer
- [ ] Vercel deployment
- [ ] Lighthouse benchmark
- [ ] Applitools
- [ ] Sentry
- [ ] Winston
- [ ] Playwright
- [ ] Faker
- [ ] lodash
- [ ] CVA
- [ ] Styled Component
- [ ] WhiteSource Renovate
- [ ] Radix UI / Headless UI

**Comment by AhmadHRai** [comment]
I think we should refrain from choosing a UI library for this template. And any other opinionated library/structure.

**Comment by nabily4e-dev** [comment]
> I think we should refrain from choosing a UI library for this template. And any other opinionated library/structure.

I would definitely go with postgreSQL!

[Vercel Postgres:](https://vercel.com/guides/nextjs-prisma-postgres) A managed PostgreSQL database service that is fully compatible with Next.js and Prisma. Vercel Postgres provides high availability, scalability, and security for your data. You can easily connect to your database from your Next.js app using environment variables and deploy your changes with zero downtime.
